// Code generated by tygo. DO NOT EDIT.

//////////
// source: ai.go

export interface AIValidateKeyRequest {
  provider: string;
  api_key: string;
}
export interface AIValidateKeyResponse {
  valid: boolean;
  error?: string;
  models?: number /* int */;
}
/**
 * ParseResumeResponse is the structured data extracted from a resume by the LLM.
 */
export interface ParseResumeResponse {
  name: string;
  email: string;
  location: string;
  linkedin_url?: string;
  github_url?: string;
  suggested_include: string[];
  suggested_exclude: string[];
  suggested_work_types: string[];
  suggested_location_keywords: string[];
  resume: ResumeInfoResponse;
}
export interface AIInfoResponse {
  provider: string;
  enabled: boolean;
  has_api_key: boolean; // true if a key is stored (never returns the key itself)
  user_name: string;
  user_email: string;
  user_location: string;
  user_linkedin: string;
  user_github: string;
}
export interface AIUpdateRequest {
  provider?: string;
  api_key?: string; // set to update, null/omit to keep existing
  enabled?: boolean;
  user_name?: string;
  user_email?: string;
  user_location?: string;
  user_linkedin?: string;
  user_github?: string;
}
/**
 * OnboardingCompleteRequest is the final step of the wizard.
 */
export interface OnboardingCompleteRequest {
  /**
   * User profile
   */
  user_name: string;
  user_email: string;
  user_location: string;
  user_linkedin?: string;
  user_github?: string;
  /**
   * Relevance preferences
   */
  include_keywords: StringSlice;
  exclude_keywords: StringSlice;
  location_keywords: StringSlice;
  work_types: StringSlice;
  max_days_old: number /* int */;
  /**
   * Scan settings
   */
  scan_enabled: boolean;
  scan_cron_expr: string;
  scan_timezone: string;
}

//////////
// source: auth.go

export interface LoginRequest {
  password: string;
}
export interface SetupRequest {
  password: string;
}
export interface ChangePasswordRequest {
  current_password: string;
  new_password: string;
}

//////////
// source: company.go

export interface Company {
  id: number /* uint */;
  name: string;
  careers_url: string;
  ats_type: string;
  ats_slug: string;
  region: string;
  location: string;
  active: boolean;
  last_scanned_at?: any /* time.Time */;
  created_at: any /* time.Time */;
  updated_at: any /* time.Time */;
}

//////////
// source: config.go

export type StringSlice = string[];
export interface Config {
  setup_complete: boolean;
  /**
   * OIDC (optional)
   */
  oidc_enabled: boolean;
  oidc_provider_url: string;
  oidc_client_id: string;
  /**
   * AI Provider
   */
  ai_provider: string;
  ai_enabled: boolean;
  /**
   * User Profile (extracted from resume or entered manually)
   */
  user_name: string;
  user_email: string;
  user_location: string;
  user_linkedin: string;
  user_github: string;
  /**
   * Scheduled scanning
   */
  scan_enabled: boolean;
  scan_cron_expr: string;
  scan_timezone: string;
  /**
   * Relevance preferences
   */
  include_keywords: StringSlice;
  exclude_keywords: StringSlice;
  location_keywords: StringSlice;
  work_types: StringSlice;
  employment_type: string;
  max_days_old: number /* int */;
  created_at: any /* time.Time */;
  updated_at: any /* time.Time */;
}

//////////
// source: response.go

export interface AuthStatusResponse {
  authenticated: boolean;
  setup_complete: boolean;
  oidc_enabled: boolean;
  oidc_provider_url?: string;
}
export interface AuthTokenResponse {
  token: string;
}
export interface ErrorResponse {
  error: string;
}
export interface MatchDetails {
  include_score: number /* int */;
  bonus_score: number /* int */;
  total_score: number /* int */;
  recency_factor: number /* float64 */;
  adjusted_score: number /* float64 */;
  matched_keywords: number /* int */;
  total_keywords: number /* int */;
  percent: number /* int */;
}
export interface RoleListItem {
  id: number /* uint */;
  company_id: number /* uint */;
  company_name: string;
  title: string;
  department: string;
  location: string;
  posted_at?: any /* time.Time */;
  relevance_score: number /* int */;
  match_percent: number /* int */;
  is_hidden: boolean;
  is_interested: boolean;
}
export interface PaginationInfo {
  total: number /* int */;
  page: number /* int */;
  per_page: number /* int */;
  total_pages: number /* int */;
}
export interface RoleListResponse {
  data: RoleListItem[];
  pagination: PaginationInfo;
  total_all: number /* int */;
}
export interface RoleDetailResponse {
  id: number /* uint */;
  company_id: number /* uint */;
  company_name: string;
  title: string;
  department: string;
  location: string;
  description: string;
  description_format: string;
  url: string;
  posted_at?: any /* time.Time */;
  relevance_score: number /* int */;
  match_percent: number /* int */;
  match_reasons?: string[];
  match_details?: MatchDetails;
  is_hidden: boolean;
  is_interested: boolean;
}

//////////
// source: resume.go

/**
 * Resume stores the extracted, searchable text from an uploaded resume.
 * The application is currently single-user, so the most recently uploaded
 * resume is used when tailoring a role.
 */
export interface Resume {
  id: number /* uint */;
  filename: string;
  media_type: string;
  created_at: any /* time.Time */;
  updated_at: any /* time.Time */;
}
/**
 * ResumeInfoResponse intentionally excludes the original resume text.
 */
export interface ResumeInfoResponse {
  id: number /* uint */;
  filename: string;
  media_type: string;
  created_at: any /* time.Time */;
}
export interface ResumeHeader {
  name: string;
  contact: string[];
}
export interface ResumeEntry {
  title: string;
  organization: string;
  location: string;
  date_range: string;
  highlights: string[];
}
export interface ResumeSection {
  heading: string;
  kind: string;
  entries: ResumeEntry[];
  items: string[];
}
/**
 * ResumeDocument is a layout-ready representation of a resume. Content is
 * retained only for backward compatibility with previously generated records.
 */
export interface ResumeDocument {
  content?: string;
  header: ResumeHeader;
  summary: string;
  sections: ResumeSection[];
}
/**
 * TailoredResume persists a generated document for a role and source resume.
 * Regenerating replaces the document for that pair while preserving its ID.
 */
export interface TailoredResume {
  id: number /* uint */;
  resume_id: number /* uint */;
  role_id: number /* uint */;
  document: ResumeDocument;
  created_at: any /* time.Time */;
  updated_at: any /* time.Time */;
}
export interface TailoredResumeResponse {
  id: number /* uint */;
  resume_id: number /* uint */;
  role_id: number /* uint */;
  document: ResumeDocument;
  created_at: any /* time.Time */;
  updated_at: any /* time.Time */;
}

//////////
// source: role.go

export interface Role {
  id: number /* uint */;
  company_id: number /* uint */;
  company: Company;
  url: string;
  title: string;
  department: string;
  location: string;
  description: string;
  description_format: string;
  posted_at?: any /* time.Time */;
  status: string;
  is_hidden: boolean;
  is_interested: boolean;
  created_at: any /* time.Time */;
  updated_at: any /* time.Time */;
}

//////////
// source: scan_job.go

/**
 * ScanJob tracks a background scan run.
 * Status: pending → running → completed | failed
 */
export interface ScanJob {
  id: number /* uint */;
  status: string;
  results?: string; // JSON-encoded []ScanResult
  error?: string;
  duration_ms: number /* int64 */;
  total_companies: number /* int */;
  completed_companies: number /* int */;
  started_at?: any /* time.Time */;
  completed_at?: any /* time.Time */;
  created_at: any /* time.Time */;
  updated_at: any /* time.Time */;
}
/**
 * ScanResult is the public DTO for a single company scan result.
 */
export interface ScanResult {
  company_name: string;
  new_roles: number /* int */;
  total_roles: number /* int */;
  error?: string;
}
/**
 * ScanJobResponse is the public DTO returned by scan endpoints.
 */
export interface ScanJobResponse {
  id: number /* uint */;
  status: string;
  results?: ScanResult[];
  error?: string;
  duration_ms: number /* int64 */;
  total_companies: number /* int */;
  completed_companies: number /* int */;
  total_new_roles: number /* int */;
  total_roles: number /* int */;
  started_at?: any /* time.Time */;
  completed_at?: any /* time.Time */;
  created_at: any /* time.Time */;
}

//////////
// source: session.go

export interface Session {
  created_at: any /* time.Time */;
}

//////////
// source: settings.go

/**
 * SettingsResponse returns the user's preferences (password hash excluded).
 */
export interface SettingsResponse {
  include_keywords: StringSlice;
  exclude_keywords: StringSlice;
  location_keywords: StringSlice;
  work_types: StringSlice;
  employment_type: string;
  max_days_old: number /* int */;
  scan_enabled: boolean;
  scan_cron_expr: string;
  scan_timezone: string;
  next_scan_at?: any /* time.Time */;
}
/**
 * SettingsUpdateRequest is the request body for PUT /api/settings.
 */
export interface SettingsUpdateRequest {
  include_keywords?: StringSlice;
  exclude_keywords?: StringSlice;
  location_keywords?: StringSlice;
  work_types?: StringSlice;
  employment_type?: string;
  max_days_old?: number /* int */;
  scan_enabled?: boolean;
  scan_cron_expr?: string;
  scan_timezone?: string;
}
