import type {
	AIInfoResponse,
	AuthStatusResponse,
	RoleDetailResponse,
	RoleListResponse,
	ScanJobResponse,
	SettingsResponse,
} from "../../types/api.gen";

export const fixtures = {
	authStatus: {
		authenticated: true,
		setup_complete: true,
		oidc_enabled: false,
	} satisfies AuthStatusResponse,
	roleList: {
		data: [
			{
				id: 1,
				company_id: 1,
				company_name: "Acme",
				title: "Frontend Engineer",
				department: "Engineering",
				location: "Remote",
				relevance_score: 95,
				match_percent: 95,
				is_hidden: false,
				is_interested: false,
			},
		],
		pagination: { total: 1, page: 1, per_page: 25, total_pages: 1 },
		total_all: 1,
	} satisfies RoleListResponse,
	roleDetail: {
		id: 1,
		company_id: 1,
		company_name: "Acme",
		title: "Frontend Engineer",
		department: "Engineering",
		location: "Remote",
		description: "Build excellent user experiences.",
		description_format: "plain_text",
		url: "https://example.com/jobs/1",
		relevance_score: 95,
		match_percent: 95,
		is_hidden: false,
		is_interested: false,
	} satisfies RoleDetailResponse,
	settings: {
		include_keywords: ["TypeScript"],
		exclude_keywords: [],
		location_keywords: ["Remote"],
		work_types: ["remote"],
		employment_type: "full_time",
		max_days_old: 30,
		scan_enabled: true,
		scan_cron_expr: "0 9 * * *",
		scan_timezone: "UTC",
	} satisfies SettingsResponse,
	scanJob: {
		id: 1,
		status: "completed",
		duration_ms: 100,
		total_companies: 1,
		completed_companies: 1,
		total_new_roles: 1,
		total_roles: 1,
		created_at: "2026-01-01T00:00:00Z",
	} satisfies ScanJobResponse,
	aiSettings: {
		provider: "openai",
		enabled: true,
		has_api_key: true,
		user_name: "Test User",
		user_email: "test@example.com",
		user_location: "Remote",
		user_linkedin: "",
		user_github: "",
	} satisfies AIInfoResponse,
};
